uploads = []

[[generated]]
id = "BQMNSHFoBOhIGv-udIaby"
uri = "file://artifacts/tsos-pitch/public/hero-school.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DJRPCR5syTTiPD-Hze-xT"
uri = "file://artifacts/tsos-pitch/public/africa-map.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cyggA5b9DVa-LdQ98OFAN"
uri = "file://artifacts/tsos-pitch/public/sync-diagram.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "cLN_SMc38GNBCYdUUUdpU"
uri = "file://TSOS_User_Guide.md"
type = "text"
title = "TSOS Complete Step-by-Step User Guide"

[[outputs]]
id = "wGXbZbP5fJbjS590Q0QSB"
uri = "file://TSOS_Project_Documentation.md"
type = "text"
title = "TSOS — Complete Project Documentation"

[[outputs]]
id = "yax4gVp9YizfcJGWRXiiH"
uri = "file://TSOS_project.tar.gz"
type = "unspecified"
title = "TSOS — Full Project Source Code (tar.gz)"

[[outputs]]
id = "imjiEPMRl-tn29sSl1X9j"
uri = "file://TERMS_OF_SERVICE_MOU.md"
type = "text"
title = "TSOS — Terms & Conditions Memorandum of Understanding"

[[outputs]]
id = "3TZOIz0LHISPe4JZylVQF"
uri = "file://.local/outputs/TSOS-Pitch-Deck.pptx"
type = "slides"
title = "TSOS Pitch Deck — 16 slides"

[[outputs]]
id = "qMW0vVa-df8pkHKWbhq5J"
uri = "file://.local/outputs/TSOS-App-Guide.pptx"
type = "slides"
title = "TSOS App Guide (PPTX)"
