export default function Slide09Teacher() {
  return (
    <div
      style={{
        width: "100vw",
        height: "100vh",
        overflow: "hidden",
        backgroundColor: "#0C0F1A",
        fontFamily: "'Plus Jakarta Sans', sans-serif",
        position: "relative",
        color: "#FFFFFF",
      }}
    >
      <div style={{ position: "absolute", top: "5vh", left: "20vw", width: "45vw", height: "45vw", borderRadius: "50%", background: "radial-gradient(circle, rgba(124,107,240,0.14) 0%, rgba(124,107,240,0) 70%)" }} />
      <div style={{ position: "absolute", inset: 0, backgroundImage: "linear-gradient(rgba(255,255,255,0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.025) 1px, transparent 1px)", backgroundSize: "4vw 4vw", pointerEvents: "none" }} />

      <div style={{ position: "absolute", top: "5vh", left: "5vw", display: "flex", alignItems: "center", gap: "1vw", zIndex: 10 }}>
        <div style={{ width: "2vw", height: "2vw", backgroundColor: "#4F7FFF", borderRadius: "0.4vw" }} />
        <div style={{ fontSize: "1.2vw", fontWeight: 700, letterSpacing: "-0.02em" }}>TSOS</div>
      </div>
      <div style={{ position: "absolute", top: "5vh", right: "5vw", fontSize: "1vw", color: "rgba(255,255,255,0.4)", zIndex: 10 }}>2026</div>

      <div
        style={{
          position: "relative",
          zIndex: 10,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          height: "100vh",
          paddingLeft: "5vw",
          paddingRight: "5vw",
          gap: "3.5vh",
        }}
      >
        <div style={{ textAlign: "center" }}>
          <div
            style={{
              display: "inline-block",
              padding: "0.5vh 1.2vw",
              backgroundColor: "rgba(124,107,240,0.12)",
              border: "1px solid rgba(124,107,240,0.3)",
              borderRadius: "2vw",
              color: "#7C6BF0",
              fontSize: "0.9vw",
              fontWeight: 600,
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              marginBottom: "2vh",
            }}
          >
            Teacher Portal
          </div>
          <h2 style={{ fontSize: "4vw", fontWeight: 800, margin: 0, lineHeight: 1.1, letterSpacing: "-0.03em", textWrap: "balance" }}>
            A dedicated experience for{" "}
            <span style={{ color: "#7C6BF0" }}>classroom teachers</span>
          </h2>
          <p style={{ fontSize: "1.25vw", fontWeight: 300, color: "rgba(255,255,255,0.55)", margin: "1.5vh 0 0", lineHeight: 1.5, maxWidth: "55vw" }}>
            Separate login, separate dashboard. Teachers only see what they need.
          </p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "1.5vw", width: "88vw" }}>
          {[
            { title: "Separate Login", desc: "Teacher credentials generated by school admin — shown once, bcrypt-hashed", color: "#7C6BF0" },
            { title: "Score Entry", desc: "Classwork /10 · Test /20 · Homework /5 · Project /5 · Exam /60 — auto-totaled", color: "#4F7FFF" },
            { title: "GPS Check-in", desc: "Haversine validation against school GPS coordinates — no manual override", color: "#34D399" },
            { title: "Timetable View", desc: "Weekly day-tab view — homeroom sees all slots, subject teachers see own subjects", color: "#FACC15" },
            { title: "Announcements", desc: "Social share buttons (WhatsApp/FB/X), unread count badge, clickable inbox", color: "#F87171" },
            { title: "Admin Role Access", desc: "Head teachers and finance officers switch to admin view in one click — no second login required", color: "#FB923C" },
          ].map((item) => (
            <div
              key={item.title}
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "1.2vh",
                padding: "2.5vh 1.8vw",
                backgroundColor: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.07)",
                borderRadius: "0.8vw",
                borderBottom: `2px solid ${item.color}`,
              }}
            >
              <div style={{ fontSize: "1.1vw", fontWeight: 700, color: item.color }}>{item.title}</div>
              <div style={{ fontSize: "0.95vw", fontWeight: 300, color: "rgba(255,255,255,0.55)", lineHeight: 1.5 }}>{item.desc}</div>
            </div>
          ))}
        </div>
      </div>

      <div style={{ position: "absolute", bottom: "4vh", left: "5vw", fontSize: "0.9vw", color: "rgba(255,255,255,0.3)", letterSpacing: "0.08em" }}>TORRENTIAL SCHOOL OPERATIONS SUITE</div>
      <div style={{ position: "absolute", bottom: "4vh", right: "5vw", fontSize: "0.9vw", color: "rgba(255,255,255,0.3)" }}>09 / 17</div>
    </div>
  );
}
